[package]
name = "edn-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.21"
edn-rs = { git = "https://github.com/Grinkers/edn-rs.git", branch = "arbitrarynums" }
